### ISSUE TITLE
Adding the ability to not upgrade certain packages to avoid compatibility issues

### ISSUE THREAD

**Issue by IlyasKhallouki** [Otas02CZ/pip_package_updater#2]
Hey!
I saw your project and I thought it was really interesting. A package updater is definitely a tool I would use. However, I think there's room for improvement. For example, we could add compatibility checking and give users the option to skip upgrading certain packages if they want.
I would be happy to contribute to this project. Just let me know if you're open to collaboration!

**Comment by Otas02CZ** [comment]
Hi, thanks for the message and interest. However I am not planning on developing this tool as I don't need it anymore and don't even do any projects in python these days. It might be better for you if you just forked it or start a new as it's just a few lines.
Anyway thanks for the interest and have a nice day.
